GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "name": "Sodgerel",
    "email": "sodoo75@gmail.com",
    "createdOn": "2010-01-01"
}

###

DELETE  http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "id": "641144550482cf84f9b52419"
}

###