###

GET http://localhost:8080/admin/user HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/admin/register HTTP/1.1
Content-Type: application/json

    {
    "email": "Sodoo333333@gmail.com",
    "password" : "1234"
    }

###

POST http://localhost:8080/admin/login HTTP/1.1
Content-Type: application/json

     {
    "email": "sodoo775@gmail.com",
    "password" : "123"
    }

###
