###

POST http://localhost:8080/api/unprotected HTTP/1.1
Content-Type: application/json

    {
    "token" : ""
    }

###

POST http://localhost:8080/api/protected HTTP/1.1
Content-Type: application/json

    {
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQxYTY4NTA1MjVhMTc3M2JlZWY1MGU1IiwiZW1haWwiOiJTb2RvbzMzMzMzM0BnbWFpbC5jb20iLCJpYXQiOjE2Nzk1MzI1MTEsImV4cCI6MTY3OTUzMjUxMX0.usjYUSpOPAMcQc80vK5LZs6G29o1HTcWjzSViWE_us0"
    }

###
