###

GET http://localhost:8080/todo/list HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/todo/create HTTP/1.1
Content-Type: application/json

    {
    "name": "Reading",
    "checked": false,
    "category": "6419645d03a916ef5bb2454e"
    }

###

DELETE  http://localhost:8080/todo/delete HTTP/1.1
Content-Type: application/json

{"checked": true}

###

PUT http://localhost:8080/todo/update HTTP/1.1
Content-Type: application/json

[
    {"checked": true},
    {"name": "Cleaning"}
]
    
###